source "https://supermarket.chef.io"

cookbook 'timezone-ii', '~> 0.2.0'
cookbook 'selinux', '~> 1.0.3'
cookbook 'mysql', '~> 8.3.1'
cookbook 'php', '~> 3.0.0'
cookbook 'composer', '~> 2.5.2'
cookbook 'apache2', '~> 3.3.0'
